# Generated by Django 4.2.6 on 2023-11-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_analyzer', '0003_alter_user_access_token_alter_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.IntegerField(null=True),
        ),
    ]
