# Generated by Django 4.2.6 on 2023-11-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_analyzer', '0006_alter_artist_uri_alter_image_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_playlists', to='spotify_analyzer.user'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_playlists', to='spotify_analyzer.user'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlist_appearances', to='spotify_analyzer.track'),
        ),
    ]
