# Generated by Django 4.2.6 on 2023-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_analyzer', '0009_album_album_type_album_name_album_total_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
